name: piper-vr
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pyyaml
  - matplotlib
  - pip
  - pip:
      - piper-sdk
      - pure-python-adb
      - rospkg
      - meshcat
      - imageio-ffmpeg
